name: NYCMonkeypox_Model
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic=1.8.1
  - attrs=22.1.0
  - autopage=0.5.1
  - backports=1.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - cliff=3.10.1
  - cmaes=0.8.2
  - cmd2=2.4.2
  - colorama=0.4.5
  - colorlog=6.6.0
  - cycler=0.11.0
  - fonttools=4.25.0
  - freetype=2.10.4
  - glib=2.69.1
  - greenlet=1.1.2
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icc_rt=2019.0.0
  - icu=58.2
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libtiff=4.2.0
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - mako=1.2.1
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - numexpr=2.8.3
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openssl=1.1.1q
  - optuna=2.10.1
  - packaging=21.3
  - pandas=1.4.3
  - pbr=5.10.0
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.1.2
  - ply=3.11
  - prettytable=3.3.0
  - pyparsing=3.0.4
  - pyperclip=1.8.2
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyreadline3=3.4.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2022.1
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - scipy=1.7.3
  - setuptools=61.2.0
  - sip=6.6.2
  - six=1.16.0
  - sqlalchemy=1.4.40
  - sqlite=3.39.2
  - stevedore=4.0.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.64.0
  - tzdata=2022a
  - vc=14.2
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2
